export const actionConstants = {
    INCREASE_COUNTER: "INCREASE_COUNTER",
    DECREASE_COUNTER: "DECREASE_COUNTER",
    INCREASE_NUMBER: "INCREASE_NUMBER",
    DECREASE_NUMBER: "DECREASE_NUMBER",
    FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
}